In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

In [3]:
df = pd.read_csv('_slash_mavros_slash_global_position_slash_raw_slash_gps_vel.csv')

In [4]:
df.head(5)

rosbagTimestamp  seq        secs      nsecs        xl        yl  zl  \
0     1.570000e+18   53  1574069785  858138123 -0.137454  0.184408   0   
1     1.570000e+18   54  1574069786  110338604 -0.251003  0.336746   0   
2     1.570000e+18   55  1574069786  356408699 -0.107573  0.144320   0   
3     1.570000e+18   56  1574069786  578747487 -0.155383  0.208462   0   
4     1.570000e+18   57  1574069786  823320336 -0.011953  0.016036   0   

   normality  
0          1  
1          1  
2          1  
3          1  
4          1

In [26]:
df = df.reindex(np.random.permutation(df.index))


In [27]:
X = df.loc[:,['xl','yl']]
y = df.loc[:,['normality']]

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [29]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [43]:
pred = model.predict(X_test)
score = model.score(X_test,y_test)
print(score)

0.9379310344827586


In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[ 13,   5],
       [  4, 123]], dtype=int64)

In [75]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
scaler.transform(X_test)

array([[0.64170597, 0.22193821],
       [0.52650966, 0.464172  ],
       [0.65840712, 0.2031987 ],
       [0.63646978, 0.23294883],
       [0.64825122, 0.20817492],
       [0.64170597, 0.22193821],
       [0.71031344, 0.23054659],
       [0.61290689, 0.28249666],
       [0.62468834, 0.25772275],
       [0.61814309, 0.27148603],
       [0.63385168, 0.23845415],
       [0.61421594, 0.279744  ],
       [0.62207024, 0.26322806],
       [0.60897975, 0.29075463],
       [0.63385168, 0.23845415],
       [0.63385168, 0.23845415],
       [0.59981641, 0.31002322],
       [0.63254263, 0.2412068 ],
       [0.64301502, 0.21918555],
       [0.62730643, 0.25221743],
       [0.62337929, 0.2604754 ],
       [0.62207024, 0.26322806],
       [0.62861548, 0.24946477],
       [0.67086464, 0.20976219],
       [0.85149864, 0.30493284],
       [0.64432407, 0.21643289],
       [0.63777883, 0.23019618],
       [0.60636165, 0.29625994],
       [0.59850736, 0.31277588],
       [0.54448835, 0.15336095],
       [0.

In [77]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model = model.fit(X_train,y_train)


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [78]:
pred = model.predict(X_test)
score = model.score(X_test,y_test)
print(score)

0.8758620689655172


In [79]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[  0,  18],
       [  0, 127]], dtype=int64)